#---------------------------------TESTING--------------------------------

FROM node:25-bullseye

WORKDIR /app

ENV NODE_ENV=development
ENV FORCE_COLOR=1

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src
COPY test ./src/test

RUN npm run build

# CMD ["tail", "-f"]
CMD ["npm", "run", "test"]
